version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting the pre-build phase..."
  build:
    commands:
      - echo "Starting the build phase..."
  post_build:
    commands:
      - echo "Starting the post-build phase..."
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: '.'
